-- -- treesitter
-- require('nvim-treesitter.configs').setup(
--   {
--     ensure_installed = "maintained",
--     highlight = {
--       enable = true,
--       disable = {},
--     },
--   }
-- )

-- -- lsp
-- local nvim_lsp = require('lspconfig')
-- local on_attach = function(_, bufnr)
--   require('diagnostic').on_attach()
--   require('completion').on_attach()
--   local opts = { noremap=true, silent=true }
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>xD', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>xr', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>xd', '<cmd>lua vim.lsp.util.show_line_diagnostics()<CR>', opts)
--   vim.api.nvim_buf_set_keymap(bufnr, 'n', '<C-h>', '<cmd>LspShowLineDiagnostics<CR>', opts)
-- end

-- -- local servers = {'jsonls', 'pyls_ms', 'vimls', 'ccls', 'tsserver', 'cssls', 'html', 'jdtls', 'sumneko_lua'}
-- local servers = {'jsonls', 'pyls_ms', 'vimls', 'clangd', 'tsserver', 'cssls', 'html', 'jdtls', 'sumneko_lua'}
-- for _, lsp in ipairs(servers) do
--   nvim_lsp[lsp].setup {
--     on_attach = on_attach,
--   }
-- end

-- vim.api.nvim_command('command! -buffer -nargs=0 LspShowLineDiagnostics lua require([[jumpLoc]]).openLineDiagnostics()')
-- vim.api.nvim_command([[command! Format execute 'lua vim.lsp.buf.formatting()']])

-- vim.g.completion_confirm_key = '<C-y>'
-- vim.g.completion_matching_strategy_list = {'exact', 'substring', 'fuzzy'}
-- vim.g.completion_enable_snippet = 'UltiSnips'
-- vim.g.completion_matching_smart_case = 1
-- vim.g.completion_trigger_on_delete = 1
